// Central sample document content used across the app.
// Keep this single source of truth so updates propagate everywhere.
export const SAMPLE_DOC = `# Welcome to Tideflow

This sample shows you the core features. You can safely delete it or reset it any time.

## 📄 What You Are Seeing
Left side: a live Markdown editor.  
Right side: an on-demand PDF preview generated by Typst.

Edits auto-render after a short debounce (shown in the toolbar). Press Render for immediate refresh.

## 🧭 Table of Contents
Toggle TOC: Open 🎨 Design > enable "Table of contents".  
When off: no outline pages are emitted.  
When on: a single outline will appear at the start.

## 📐 Layout & Margins
Open 🎨 Design to adjust: paper size, margins (x / y), fonts, image defaults.
Margins accept units like: cm, mm, in, pt (e.g. 2cm, 1in, 24pt).

## 🔤 Fonts
Use the Font controls in the mini toolbar: 
1. Choose Apply: Document
2. Pick a font (e.g. New Computer Modern, Liberation Mono)
The entire PDF will re-render with that font.
Use Apply: Selection to locally wrap text with a font span.

## 🖼 Images
Paste (Ctrl+V) or drag & drop an image file.  
It is copied to your project assets folder and Markdown is inserted automatically.

Default width & alignment are controlled in 🎨 Design.

## 📑 Page Break
Click the ⤓⤒ button in the toolbar to insert a page break marker.

## 🧪 Math
Inline: $E = mc^2$  
Block math:
$$
\\int_0^1 x^2 \\; dx = \\tfrac{1}{3}
$$

## Code Blocks
Triple backticks start a fenced block:
\`\`\`python
def hello(name: str):
    print(f("Hello {name}"))
\`\`\`

## ✅ Tasks / Lists
- [x] Understand basics
- [ ] Write your own notes

## 🧷 Links & Formatting
Use the shortcuts: Ctrl+B (bold), Ctrl+I (italic), Ctrl+K (link), Ctrl+\` (inline code).

## 📤 Export
When a PDF has rendered you can click "📄 Export PDF" in the top toolbar to save it.

## ♻ Reset / Clear Cache
Use the new Reset button (top toolbar) to:
- Clear session (open tabs & scroll state)
- Return to a fresh copy of this sample
- Clear the current compiled PDF

## 🧪 Try It Now
Make some edits, toggle the TOC, change fonts, export a PDF, then hit Reset to start over.

Happy writing!`;
