import type { Preferences } from './types';
import { defaultPreferences } from './stores/preferencesStore';

export interface ThemeDefinition {
  id: string;
  name: string;
  description: string;
  preferences: Preferences;
}

const mergePreferences = (overrides: Partial<Preferences>): Preferences => {
  return {
    ...defaultPreferences,
    ...overrides,
    margin: {
      ...defaultPreferences.margin,
      ...(overrides.margin ?? {}),
    },
    fonts: {
      ...defaultPreferences.fonts,
      ...(overrides.fonts ?? {}),
    },
  };
};

export const themePresets: Record<string, ThemeDefinition> = {
  default: {
    id: 'default',
    name: 'Default',
    description: 'Clean and professional serif layout with balanced spacing',
    preferences: mergePreferences({
      theme_id: 'default',
      fonts: { main: 'New Computer Modern', mono: 'New Computer Modern Mono' },
      font_size: 11,
      page_bg_color: '#ffffff',
      font_color: '#000000',
      heading_scale: 1.0,
      accent_color: '#2d3e50',
      margin: { x: '2.5cm', y: '3cm' },
      papersize: 'a4',
      toc: false,
      cover_page: false,
      number_sections: false,
      default_image_width: '75%',
      default_image_alignment: 'center',
    }),
  },
  
  minimal: {
    id: 'minimal',
    name: 'Minimal',
    description: 'Ultra-clean sans-serif with maximum breathing room and wide margins',
    preferences: mergePreferences({
      theme_id: 'minimal',
      fonts: { main: 'Verdana', mono: 'Courier New' },
      font_size: 12,
      page_bg_color: '#fafafa',
      font_color: '#1a1a1a',
      heading_scale: 1.1,
      accent_color: '#787878',
      margin: { x: '4cm', y: '4.5cm' },
      papersize: 'a4',
      toc: false,
      cover_page: false,
      number_sections: false,
      default_image_width: '55%',
      default_image_alignment: 'center',
    }),
  },
  
  compact: {
    id: 'compact',
    name: 'Compact',
    description: 'Dense technical layout with minimal margins for maximum content',
    preferences: mergePreferences({
      theme_id: 'compact',
      fonts: { main: 'Arial', mono: 'Courier New' },
      font_size: 10,
      page_bg_color: '#ffffff',
      font_color: '#000000',
      heading_scale: 0.9,
      accent_color: '#000000',
      margin: { x: '1.2cm', y: '1.5cm' },
      papersize: 'a4',
      toc: false,
      cover_page: false,
      number_sections: false,
      default_image_width: '95%',
      default_image_alignment: 'left',
    }),
  },
  
  elegant: {
    id: 'elegant',
    name: 'Elegant',
    description: 'Sophisticated serif with generous margins and book-like feel',
    preferences: mergePreferences({
      theme_id: 'elegant',
      fonts: { main: 'Georgia', mono: 'Courier New' },
      font_size: 12,
      page_bg_color: '#fffef8',
      font_color: '#2d2d2d',
      heading_scale: 1.15,
      accent_color: '#192337',
      margin: { x: '3.5cm', y: '4cm' },
      papersize: 'a4',
      toc: false,
      cover_page: false,
      number_sections: false,
      default_image_width: '65%',
      default_image_alignment: 'center',
    }),
  },
  
  technical: {
    id: 'technical',
    name: 'Technical',
    description: 'Monospace body font for code-heavy documents with numbered sections',
    preferences: mergePreferences({
      theme_id: 'technical',
      fonts: { main: 'Courier New', mono: 'Courier New' },
      font_size: 10,
      page_bg_color: '#f5f5f5',
      font_color: '#1e293b',
      heading_scale: 1.0,
      accent_color: '#006496',
      margin: { x: '2cm', y: '2.5cm' },
      papersize: 'a4',
      toc: false,
      cover_page: false,
      number_sections: false,
      default_image_width: '85%',
      default_image_alignment: 'left',
    }),
  },
  
  magazine: {
    id: 'magazine',
    name: 'Magazine',
    description: 'Bold editorial style with tight margins and full-width images',
    preferences: mergePreferences({
      theme_id: 'magazine',
      fonts: { main: 'Trebuchet MS', mono: 'Courier New' },
      font_size: 11,
      page_bg_color: '#ffffff',
      font_color: '#0a0a0a',
      heading_scale: 1.3,
      accent_color: '#0064b4',
      margin: { x: '1.5cm', y: '1.8cm' },
      papersize: 'a4',
      toc: false,
      cover_page: false,
      number_sections: false,
      default_image_width: '100%',
      default_image_alignment: 'center',
    }),
  },
  
  academic: {
    id: 'academic',
    name: 'Academic',
    description: 'Two-column layout perfect for research papers and articles',
    preferences: mergePreferences({
      theme_id: 'academic',
      fonts: { main: 'Times New Roman', mono: 'Courier New' },
      font_size: 10,
      page_bg_color: '#ffffff',
      font_color: '#000000',
      heading_scale: 1.0,
      accent_color: '#000000',
      margin: { x: '1.8cm', y: '2.2cm' },
      papersize: 'a4',
      toc: false,
      cover_page: false,
      number_sections: false,
      default_image_width: '85%',
      default_image_alignment: 'center',
    }),
  },
  
  creative: {
    id: 'creative',
    name: 'Creative',
    description: 'Vibrant and artistic with colorful gradients and dynamic spacing',
    preferences: mergePreferences({
      theme_id: 'creative',
      fonts: { main: 'Impact', mono: 'Courier New' },
      font_size: 11,
      page_bg_color: '#fef3c7',
      font_color: '#1f2937',
      heading_scale: 1.25,
      accent_color: '#df0808',
      margin: { x: '2.5cm', y: '3cm' },
      papersize: 'a4',
      toc: false,
      cover_page: false,
      number_sections: false,
      default_image_width: '80%',
      default_image_alignment: 'center',
    }),
  },
  
  modern: {
    id: 'modern',
    name: 'Modern',
    description: 'Clean contemporary design with subtle blue accents',
    preferences: mergePreferences({
      theme_id: 'modern',
      fonts: { main: 'Arial', mono: 'Courier New' },
      font_size: 11,
      page_bg_color: '#f8fafc',
      font_color: '#0f172a',
      heading_scale: 1.1,
      accent_color: '#323232',
      margin: { x: '3cm', y: '3cm' },
      papersize: 'a4',
      toc: false,
      cover_page: false,
      number_sections: false,
      default_image_width: '75%',
      default_image_alignment: 'center',
    }),
  },
  
  serif: {
    id: 'serif',
    name: 'Serif',
    description: 'Traditional serif typography with book-like appearance',
    preferences: mergePreferences({
      theme_id: 'serif',
      fonts: { main: 'Times New Roman', mono: 'Courier New' },
      font_size: 12,
      page_bg_color: '#fffef5',
      font_color: '#1c1917',
      heading_scale: 1.15,
      accent_color: '#282828',
      margin: { x: '3.5cm', y: '3.5cm' },
      papersize: 'a4',
      toc: false,
      cover_page: false,
      number_sections: false,
      default_image_width: '70%',
      default_image_alignment: 'center',
    }),
  },
  
  notebook: {
    id: 'notebook',
    name: 'Notebook',
    description: 'Aged parchment paper with black ink and ornamental handwritten style',
    preferences: mergePreferences({
      theme_id: 'notebook',
      fonts: { main: 'Comic Sans MS', mono: 'Courier New' },
      font_size: 11,
      page_bg_color: '#f4e8d0',
      font_color: '#1a1a1a',
      heading_scale: 1.05,
      accent_color: '#2a2a2a',
      margin: { x: '3.5cm', y: '3cm' },
      papersize: 'a4',
      toc: false,
      cover_page: false,
      number_sections: false,
      default_image_width: '80%',
      default_image_alignment: 'left',
    }),
  },
  
  dark: {
    id: 'dark',
    name: 'Dark',
    description: 'White text on dark background for reduced eye strain',
    preferences: mergePreferences({
      theme_id: 'dark',
      fonts: { main: 'Verdana', mono: 'Courier New' },
      font_size: 11,
      page_bg_color: '#282828',
      font_color: '#ffffff',
      heading_scale: 1.1,
      accent_color: '#ffffff',
      margin: { x: '2.5cm', y: '3cm' },
      papersize: 'a4',
      toc: false,
      cover_page: false,
      number_sections: false,
      default_image_width: '80%',
      default_image_alignment: 'center',
    }),
  },
};

export const themeList = Object.values(themePresets);
